### ISSUE TITLE
tv features failure

### ISSUE THREAD

**Issue by HarveyGuo960817** [VALUE-Leaderboard/DataRelease#2]
Excuse me, we try to download the features, but only the tv feature cannot be connected. 

(2021-06-17 03:30:56 ERROR 404: The specified blob does not exist..)

Could you please check the release ? Thanks a lot.

**Comment by linjieli222** [comment]
@HarveyGuo960817, thank you for letting us know and sorry about inconvenience. 

We have fixed the release at our end. Please try again and let me know if there is any issues.

**Comment by linjieli222** [comment]
Closed due to inactivity.
