### ISSUE TITLE
what does 'e_1235c.npz' means?

### ISSUE THREAD

**Issue by hgzjy25** [VALUE-Leaderboard/DataRelease#3]
I have downloaded and extracted the how2 dataset features, but found some npz files with name begin with 'e' or end with 'i'. What does these names mean? 
And why #vid_name in how2_subtitles.json is larger than that in how2 feature dir?

**Comment by linjieli222** [comment]
The names starting with 'e' and 'i' are jus some random vid we used for the segmented clips when collecting annotations on Amazon MTurk. 

The subtitles are directly downloaded from YouTube automatically generated captions and segmented into 60s clips, so there are clips that are not use in annotation.  Please refer to How2R and How2QA annotations for a complete list of clips and subtitles used in these tasks. 

Sorry about the confusion. 

Please let us know if you have additional questions.

**Comment by linjieli222** [comment]
closed due to inactivities.
