### ISSUE TITLE
the ann of tv can not be download

### ISSUE THREAD

**Issue by DoubtedSteam** [VALUE-Leaderboard/DataRelease#6]
the ann of tvqa dataset can not be downloaded from the URL in the file.
would you mind providing another release?

**Comment by HenryHZY** [comment]
Hi @DoubtedSteam  Same experience as you. Have you tried to download it after closing the VPN? 
In Hong Kong, I can not currently access tvqa.cs.unc.edu. 
But I can access this website when I am in China Mainland without using VPN. That is confusing.

**Comment by DoubtedSteam** [comment]
Thanks for your advice @HenryHZY .
I still can't open the website without VPN.

**Comment by TobiasLee** [comment]
same issue, any progress here?

**Comment by TobiasLee** [comment]
well, according to https://github.com/jayleicn/TVQA/issues/20
seems that the server is down and the author does not have an ETA for now.

**Comment by jayleicn** [comment]
The data is now back in [this new link](https://nlp.cs.unc.edu/data/jielei/tvqa/tvqa_public_html/). Thanks for your patience.

Best,
Jie
